In [1]:
import torch

# 创建一个形状为 [4, 4] 的张量
tensor = torch.arange(16).reshape(4, 4)
print("原始张量：")
print(tensor)

# 进行 flatten 操作
flattened_tensor = tensor.flatten()
print("\n展平后的张量：")
print(flattened_tensor)

# 验证展平后的索引和原始张量中的对应关系
for k in range(len(flattened_tensor)):
    i, j = k // 4, k % 4
    original_value = tensor[i, j]
    flattened_value = flattened_tensor[k]
    print(f"索引 {k} 对应的值：原始张量中 [{i}, {j}] 的值为 {original_value}，展平后的张量中对应的值为 {flattened_value}")


原始张量：
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

展平后的张量：
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
索引 0 对应的值：原始张量中 [0, 0] 的值为 0，展平后的张量中对应的值为 0
索引 1 对应的值：原始张量中 [0, 1] 的值为 1，展平后的张量中对应的值为 1
索引 2 对应的值：原始张量中 [0, 2] 的值为 2，展平后的张量中对应的值为 2
索引 3 对应的值：原始张量中 [0, 3] 的值为 3，展平后的张量中对应的值为 3
索引 4 对应的值：原始张量中 [1, 0] 的值为 4，展平后的张量中对应的值为 4
索引 5 对应的值：原始张量中 [1, 1] 的值为 5，展平后的张量中对应的值为 5
索引 6 对应的值：原始张量中 [1, 2] 的值为 6，展平后的张量中对应的值为 6
索引 7 对应的值：原始张量中 [1, 3] 的值为 7，展平后的张量中对应的值为 7
索引 8 对应的值：原始张量中 [2, 0] 的值为 8，展平后的张量中对应的值为 8
索引 9 对应的值：原始张量中 [2, 1] 的值为 9，展平后的张量中对应的值为 9
索引 10 对应的值：原始张量中 [2, 2] 的值为 10，展平后的张量中对应的值为 10
索引 11 对应的值：原始张量中 [2, 3] 的值为 11，展平后的张量中对应的值为 11
索引 12 对应的值：原始张量中 [3, 0] 的值为 12，展平后的张量中对应的值为 12
索引 13 对应的值：原始张量中 [3, 1] 的值为 13，展平后的张量中对应的值为 13
索引 14 对应的值：原始张量中 [3, 2] 的值为 14，展平后的张量中对应的值为 14
索引 15 对应的值：原始张量中 [3, 3] 的值为 15，展平后的张量中对应的值为 15


In [14]:
import torch

# 创建一个形状为[batch, 5, 3*3]的cat_tensor
cat_tensor = torch.arange(2*5*3*3).reshape(2, 5, 3*3)
#print('cat_tensor:', cat_tensor)

# 创建一个形状为[batch, 1]的ind
ind = torch.randint(0, 9, (2, 1)).unsqueeze(1).expand(-1,5,-1)
print('ind shape:', ind.shape)

# 使用gather函数
param_indexed = cat_tensor.gather(2, ind)

print("cat_tensor:")
print(cat_tensor)
print("\nind:")
print(ind)
print("\nparam_indexed:")
print(param_indexed)

ind shape: torch.Size([2, 5, 1])
cat_tensor:
tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
         [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23, 24, 25, 26],
         [27, 28, 29, 30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41, 42, 43, 44]],

        [[45, 46, 47, 48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59, 60, 61, 62],
         [63, 64, 65, 66, 67, 68, 69, 70, 71],
         [72, 73, 74, 75, 76, 77, 78, 79, 80],
         [81, 82, 83, 84, 85, 86, 87, 88, 89]]])

ind:
tensor([[[8],
         [8],
         [8],
         [8],
         [8]],

        [[1],
         [1],
         [1],
         [1],
         [1]]])

param_indexed:
tensor([[[ 8],
         [17],
         [26],
         [35],
         [44]],

        [[46],
         [55],
         [64],
         [73],
         [82]]])


In [18]:
rd = torch.randint(0,9,(2,2))
add = torch.randint(0,9,(2,1))
print(rd)
print(rd + add)


tensor([[ 0.5931,  1.3175],
        [-1.1474,  0.0956]])
tensor([[ 1.2476,  1.9721],
        [-0.8318,  0.4112]])
